blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.post_list,name='post_list'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
    url(r'post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/remove$', views.comment_remove, name='comment_remove'),
    url(r'^comment/(?P<pk>\d+)/approve$', views.comment_approve, name='comment_approve'),
]

board/urls.py
from django.conf.urls import url

from board import views

urlpatterns = [
    url(r'^$', views.post_list,name='post_list'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    # url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
    # url(r'post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    # url(r'post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    # url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    # url(r'^comment/(?P<pk>\d+)/remove$', views.comment_remove, name='comment_remove'),
    # url(r'^comment/(?P<pk>\d+)/approve$', views.comment_approve, name='comment_approve'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^board/', include('board.urls', namespace='board')),
    url(r'^tag/(?P<tag>.*)/$', taglink, name='taglink'),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page':'/'}),
    url(r'^accounts/register/$', UserRegister.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserRegisterDone.as_view(), name='register_done'),
]
urlpatterns += static('media', document_root= settings.MEDIA_ROOT)

board/models.py
from django.db import models
from django.utils import timezone
import os

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=50)
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Board(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    author = models.ForeignKey('auth.User')
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, null=True)

    def __str__(self):
        return self.title

class File(models.Model):
    file = models.FileField(upload_to='files/%Y/%m/%d',null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Board, null=True, on_delete=models.CASCADE)

    def filename(self):
        return os.path.basename(self.file.name)

    def delete(self, *args, **kwargs):
        self.file.delete()
        super(File, self).delete(*args, **kwargs)

    def __str__(self):
        return self.file.name

class Image(models.Model):
    image = models.ImageField(upload_to='images/%Y/%m/%d', null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Board, null=True, on_delete=models.CASCADE)

    def filename(self):
        return os.path.basename(self.image.name)

    def delete(self, *args, **kwargs):
        self.image.delete()
        super(Image, self).delete(*args, **kwargs)

    def __str__(self):
        return self.image.name

# class Image(models.Model):
#     image = models.FileField(upload_to='files/%Y/%m/%d',null=True)
#     created_date = models.DateTimeField(auto_now_add=True)
#     post = models.ForeignKey(Board, null=True, on_delete=models.CASCADE)
#
#     def filename(self):
#         return os.path.basename(self.image.name)
#
#     def delete(self, *args, **kwargs):
#         self.image.delete()
#         super(Image, self).delete(*args, **kwargs)
#
#     def __str__(self):
#         return self.image.name

board/forms.py
from django import forms
from board.models import Board, File, Image

class BoardForm(forms.ModelForm):

    class Meta:
        model = Board
        fields = ('title','author','text','category',)

class FileForm(forms.ModelForm):

    class Meta:
        model = File
        fields = ('file',)

class ImageForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = ('image',)

board/views.py
from django.shortcuts import render
from board.models import Board, Category, File, Image
from django.shortcuts import redirect, get_object_or_404
from board.forms import BoardForm, FileForm, ImageForm

# Create your views here.
def post_list(request):
    ctgry = request.GET.get('category')
    if ctgry != None:
        posts = Board.objects.filter(category__name = ctgry)
    else:
        posts = Board.objects.all()

    categories = Category.objects.all()

    return render(request, 'board/post_list.html',{'posts':posts, 'categories':categories})

def post_detail(request, pk):
    categories = Category.objects.all()
    board = get_object_or_404(Board, pk=pk)
    files = board.file_set.all()
    images = board.image_set.all()
    return render(request, 'board/post_detail.html',{'board':board, 'categories':categories,'files':files, 'images':images})

def post_new(request):
    categories = Category.objects.all()
    if request.method == 'POST':
        form = BoardForm(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()

            upfls = request.FILES.getlist('file')
            for upfls in upfls:
                file = File()
                file.file = upfls
                file.post = post
                file.save()

            upimgs = request.FILES.getlist('image')
            for upimgs in upimgs:
                image = Image()
                image.image = upimgs
                image.post = post
                image.save()

            return redirect('board:post_detail', pk=post.pk)
    else:
        form = BoardForm()
        file = FileForm()
        image = ImageForm()

    return render(request, 'board/post_edit.html',{'form':form, 'categories':categories, 'file': file, 'image': image})

def post_edit(request,pk):
    categories = Category.objects.all()
    post = get_object_or_404(Board, pk=pk)
    getfile = post.file_set.all()
    getimage = post.image_set.all()

    if request.method == 'POST':
        form = BoardForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()

            upfls = request.FILES.getlist('file')
            for upfls in upfls:
                file = File()
                file.file = upfls
                file.post = post
                file.save()

            upimgs = request.FILES.getlist('image')
            for upimgs in upimgs:
                image = Image()
                image.image = upimgs
                image.post = post
                image.save()

            return redirect('board:post_detail', pk=post.pk)
    else:
        form = BoardForm(instance=post)
        file = FileForm(instance=getfile)
        image = ImageForm(instance=getimage)

    return render(request, 'board/post_edit.html',{'form':form, 'categories':categories, 'file':file,'image':image})

board/templates/board/base.html
{% extends 'base.html' %}

{% block title %}
    <h1 style="color:#fff;"><a href="/" class="blogname">Home</a> | <a href="{% url 'board:post_list' %}" class="blogname">문건우네 게시판</a></h1>
{% endblock %}
{% block new %}
    <a href="{% url 'board:post_new' %}" class="white">새글작성</a>
{% endblock %}
{% block sub_content %}
<nav>
    <ul>
        <li><a href="{% url 'board:post_list' %}">전체보기</a></li>
        {% for ctgry in categories %}
            <li><a href="{% url 'board:post_list' %}?category={{ ctgry }}">{{ ctgry.name }}</a></li>
        {% endfor %}
    </ul>
</nav>
{% endblock %}
{% block content %}
{% endblock %}

board/templates/board/post_detail.html
{% extends 'board/base.html' %}
{% load static %}

{% block content %}
    {% if user.is_authenticated %}
    <nav>
        <a href="{% url 'board:post_edit' pk=board.pk %}">수정하기</a>
    </nav>
    {% endif %}
    <div class="detail clearfix">
        {% if board.published_date %}
            <div class="detail_publish">
                <p>{{ post.published_date }}</p>
            </div>
        {% else %}
            {% if user.is_authenticated %}
            <a href="" >배포하기</a>
            {% endif %}
        {% endif %}
        <h1>{{ board.title }}</h1>
        <p>글쓴이: {{ board.author }} | 작성일: {{ board.created_date }} | 수정일: {{ board.modified_date }}</p>
        <p>{{ board.text|linebreaksbr }}</p>
        <div>
            <h4>첨부파일</h4>
            <p>
                {% for file in files %}
                    <a href="{% get_media_prefix %}{{ file }}">{{ file.filename }}</a>
                {% endfor %}
            </p>
        </div>
        <div>
            <h4>첨부이미지</h4>
            {% for img in images %}
                <a href="{% get_media_prefix %}{{ img }}">{{ img.filename }}</a>
                <img src="{% get_media_prefix %}{{ img }}" alt="{{ img.name }}" >
            {% endfor %}
        </div>
    </div>
{% endblock %}

board/templates/board/post_edit.html
{% extends 'board/base.html' %}

{% block content %}
    <h1>새글쓰기</h1>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <p>첨부할 파일을 추가해주세요.</p>
        {{ file.as_p }}
        <p>첨부할 사진을 추가해주세요.</p>
        {{ image.as_p }}
        <button type="submit">저장</button>
    </form>
{% endblock %}

board/templates/board/post_list.html
{% extends 'board/base.html' %}

{% block content %}
<div class="board_border">
	<div class="board_list_f">
		<ol class="board_list">
		    {% for post in posts %}
		        <li><a href="{% url 'board:post_detail' pk=post.pk %}"> {{ post }} | {{ post.author }} | {{ post.created_date }} | {{ post.category }}</a></li>
		    {% endfor %}
		</ol>
	</div>
</div>
{% endblock %}
exit()