blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.post_list,name='post_list'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
    url(r'post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/remove$', views.comment_remove, name='comment_remove'),
    url(r'^comment/(?P<pk>\d+)/approve$', views.comment_approve, name='comment_approve'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^board/', include('board.urls', namespace='board')),
    url(r'^tag/(?P<tag>.*)/$', taglink, name='taglink'),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page':'/'}),
    url(r'^accounts/register/$', UserRegister.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserRegisterDone.as_view(), name='register_done'),
]
urlpatterns += static('media', document_root= settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from taggit.managers import TaggableManager
from django.utils import timezone

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    tags = TaggableManager()

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approved(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from blog.models import Post, Comment

# class PostForm(forms.Form):
#     title = forms.CharField(max_length=200)
#     text = forms.Textarea()

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title','text','tags',)

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author','text',)

blog/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView
from blog.models import Post,Comment
from django.utils import timezone
from blog.forms import PostForm, CommentForm
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from taggit.models import Tag

# Create your views here.
def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    tags = Tag.objects.all()
    return render(request, 'blog/post_list.html',{'posts':posts,'tags':tags})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    dir = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    return render(request, 'blog/post_detail.html',{'post':post,'dir':dir})

@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            # post.published_date = timezone.now()
            post.save()
            form.save_m2m()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html',{'form':form})

@login_required
def post_edit(request,pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            # post.published_date = timezone.now()
            post.save()
            form.save_m2m()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html',{'form':form})

@login_required
def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    return render(request, 'blog/post_draft_list.html',{'posts':posts})

@login_required
def post_publish(requset, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return  redirect('blog:post_detail',pk=pk)

@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blog:post_list')

def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail',pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html',{'form':form})

@login_required
def comment_remove(requset,pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('blog:post_detail', pk=comment.post.pk)

@login_required
def comment_approve(requset,pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approved()
    return redirect('blog:post_detail', pk=comment.post.pk)

blog/templates/blog/add_comment_to_post.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1 class="edit">댓글작성</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">저장</button>
    </form>
{% endblock %}

blog/templates/blog/base.html
{% extends 'base.html' %}

{% block title %}
        <h1 style="color:#fff;"><a href="/" class="blogname">Home</a> | <a href="{% url 'blog:post_list' %}" class="blogname">문건우네 블로그</a></h1>
{% endblock %}
{% block new %}
    <a href="{% url 'blog:post_new' %}" class="white">새글작성</a>
    <a href="{% url 'blog:post_draft_list' %}" class="white">초안목록</a>
{% endblock %}
{% block content %}
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    {% if user.is_authenticated %}
    <nav class="detail_edit clearfix">
        <a href="{% url 'blog:post_edit' pk=post.pk %}">수정하기</a>
    </nav>
    {% endif %}
    <div class="detail clearfix">
        {% if post.published_date %}
            <div class="detail_publish">
                <p>{{ post.published_date }}</p>
            </div>
        {% else %}
            {% if user.is_authenticated %}
            <a href="{% url 'blog:post_publish' pk=post.pk %}" class="detail_publish_post">배포하기</a>
            {% endif %}
        {% endif %}
        <h1 class="detail_title">{{ post.title }}</h1>
        <p class="detail_text">{{ post.text|linebreaksbr }}</p>
        {% for tag in post.tags.all %}
            <a href="{% url 'taglink' tag.name %}">#{{ tag }}</a>
        {% endfor %}
        {% if user.is_authenticated %}
            <a href="{% url 'blog:post_remove' pk=post.pk %}" class="detail_del">삭제하기</a>
        {% endif %}
        <hr>
        <p class="comment_name">댓글</p>
        <a href="{% url 'blog:add_comment_to_post' pk=post.pk %}" class="detail_comment">댓글달기</a>
        {% for comment in post.comments.all %}
            {% if user.is_authenticated or comment.approved_comment %}
            <div class="comment">
                <p class="comment_create">{{ comment.created_date }}</p>
                <p class="comment_author">{{ comment.author }}</p>
                <p class="comment_text">{{ comment.text|linebreaksbr }}</p>
                {% if not comment.approved_comment %}
                <a href="{% url 'blog:comment_remove' pk=comment.pk %}" class="comment_del">삭제</a>
                <a href="{% url 'blog:comment_approve' pk=comment.pk %}" class="comment_approve">승인</a>
                {% endif %}
            </div>
            {% endif %}
        {% empty%}
            <p>일등으로 댓글 달어보자! ^^7</p>
        {% endfor %}
    </div>
    <div>
        <h3>블로그 글 목록</h3>
        <ul>
            {% for dir in dir %}
                <li style="list-style:none;"><a href="{% url 'blog:post_detail' dir.pk %}">{{ dir }} | {{ dir.created_date }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="draft">
            <p class="draft_date">Created: {{ post.created_date|date:'y-m-d' }}</p>
            <h1>
                <a href="{% url 'blog:post_detail' pk=post.pk %}" class="draft_title">{{ post.title }}</a>
                {% if user.is_authenticated %}
                <a href="{% url 'blog:post_remove' pk=post.pk %}" class="draft_del">[삭제]</a>
                {% endif %}
            </h1>
            <p class="draft_text">{{ post.text | linebreaksbr }}</p>
        </div>
    {% empty %}
        <h2>초안목록이 없습니다.</h2>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1 class="edit">새글쓰기</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">저장</button>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="list">
            <h2 class="clearfix">
                <a href="{% url 'blog:post_detail' pk=post.pk %}" class="list_title">{{ post.title }} | {{ post.created_date }}</a>
                {% if user.is_authenticated %}
                <a href="{% url 'blog:post_remove' pk=post.pk %}" class="list_del">[삭제]</a>
                {% endif %}
            </h2>
            <p style="font-weight:bold;" class="list_count">댓글수 : <span class="list_conut_child">{{ post.approved_comments.count }}</span></p>
        </div>
    {% endfor %}
{% endblock %}