blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.post_list,name='post_list'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
    url(r'post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/remove$', views.comment_remove, name='comment_remove'),
    url(r'^comment/(?P<pk>\d+)/approve$', views.comment_approve, name='comment_approve'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^board/', include('board.urls', namespace='board')),
    url(r'^tag/(?P<tag>.*)/$', taglink, name='taglink'),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page':'/'}),
    url(r'^accounts/register/$', UserRegister.as_view(), name='register'),
    url(r'^accounts/register/done/$', UserRegisterDone.as_view(), name='register_done'),
]
urlpatterns += static('media', document_root= settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>문건우네</title>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.rawgit.com/moonspam/NanumSquare/master/nanumsquare.css">
</head>
<body>
    <div class="head clearfix">
        {% block title %}
        {% endblock %}
        {% if user.is_authenticated %}
        <p class="hello">안녕하세요. '{{ user.first_name }}'님</p>
        <a href="{% url 'logout' %}" class="member">Logout</a>
        <nav class="li_nav">
            {% block new %}
            {% endblock %}
        </nav>
        {% else %}
        <a href="{% url 'login' %}" class="member">Login</a>
        <a href="{% url 'register' %}" class="member" style="margin-right:3.5em;">Sign up</a>
        {% endif %}
    </div>
    {% block sub_content %}
    {% endblock %}
    {% block content %}
    {% endblock %}
    {% block home %}
    {% endblock %}
    {% block register %}
    {% endblock %}
<footer>
    <p>&copy; Powerd By c22moon.</p>
</footer>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}
<h1><a href="/" style="color:#fff;">'그'가 만든 페이지</a></h1>
{% endblock %}
{% block home %}
    <div class="home">
        <div class="home_1 home_C">
            <h2><a href="blog/">블로그 최신글</a></h2>
            <ol>
                {% for post in posts %}
                <li><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post }} | {{ post.created_date }}</a></li>
                {% endfor %}
            </ol>
        </div>
        <div class="home_2 home_C">
            <h2><a href="board/">게시판 최신글</a></h2>
            <ol>
                {% for board in boards %}
                <li><a href="{% url 'board:post_detail' pk=board.pk %}">{{ board }} | {{ board.created_date }}</a></li>
                {% endfor %}
            </ol>
        </div>
        <div class="home_C">
            <h2>Tag</h2>
            <p>
                {% for tag in tags %}
                    <a href="{% url 'taglink' tag.name %}">#{{ tag }}</a>
                {% endfor %}
            </p>
        </div>
    </div>

{% endblock %}

templates/tag_link.html
{% extends 'home.html' %}

{% block home %}
    <div class="home">
        <div class="home_1 home_C">
            <h2>'{{ tagname }}' (으)로 태그된 글입니다.</h2>
            <h3>블로그</h3>
            <ul>
                {% for post in posts %}
                <li><a href="{% url 'blog:post_detail' post.pk %}">{{ post }}|{{ post.author }}|{{ post.created_date }}</a></li>
                {% empty %}
                <li>'{{ tagname }}' (으)로 태그된 글이 없습니다.</li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}